### ISSUE TITLE
switch to using oauth2 as the authtoken is being deprecated

### ISSUE THREAD

**Issue by xsnrg** [sourcegraph/terraform-provider-site24x7#7]
https://www.site24x7.com/help/api/index.html#authentication

which states: 

```New authtokens will be deprecated by 31st August, 2019 and the existing ones will be deprecated by 30th November, 2019. Please migrate to OAuth for a more secure access.```

**Comment by keegancsmith** [comment]
@xsnrg thank you for the notice, we will look into this in July.

**Comment by hacst** [comment]
@keegancsmith Any updates on this? I might be able to contribute towards making this work in October if there isn't any other plan to tackle this.

**Comment by site24x7-old** [comment]
Hi, 

We have ready-to-use sample implementations in Golang, Python, and PowerShell for using OAuth 2.0 tokens. [Go to our community post](https://www.site24x7.com/community/migrating-to-oauth-2-0-to-authenticate-the-site24x7-rest-apis) to download the scripts.

**Comment by keegancsmith** [comment]
Sorry this slipped through the cracks. cc @sourcegraph/distribution any interest in fixing this? Otherwise I'll see if I have some bandwidth.

**Comment by uwedeportivo** [comment]
i'll do it
